### ISSUE TITLE
eservice on python 3.8 throws 400 bad client request for multipart/form-data binary requests

### ISSUE THREAD

**Issue by marcelamelara** [hyperledger-labs/private-data-objects#361]
On initialize and invoke contract calls, which send a multipart/form-data request, the HTTP server backend of the eservice returns a 400 bad request response when run using Python 3.8.10, requests 2.27.1, twisted 22.1.0.

How to reproduce:
```
pdo-test-request --ledger ${PDO_LEDGER_URL} \
    --pservice http://localhost:7001/ http://localhost:7002 http://localhost:7003 \
    --eservice-url http://localhost:7101/ \
    --logfile __screen__ --loglevel debug
```

Client debug log:
```
[17:42:56 INFO pdo.test.request] create the initial contract state
[17:42:56 DEBUG pdo.common.keys] message: h1zCNbQtFmzcdcYXiBTtyL6OsJTxwJhtmRMaw57Pfuk=19477663798EE205700FFCF0807036C9
[17:42:56 DEBUG pdo.common.keys] signature: MEQCIDADLQlflogb5utoo6uVIjFTEIrR7Ix2XrczSfeeGahLAiBLSlprLJukIvRyJhhndvuT4Tg8+/1SmZrDzhFN51gfGw==
[17:42:56 DEBUG pdo.common.keys] message: (180, 89, 215, 172, 209, 9, 241, 67, 179, 17, 253, 210, 90, 69, 158, 24)
[17:42:56 DEBUG pdo.common.keys] encrypted message: (229, 4, 236, 104, 51, 148, 127, 164, 254, 217, 221, 92, 23, 63, 71, 254, 242, 86, 252, 28, 235, 171, 188, 241, 126, 104, 36, 206, 40, 3, 31, 30, 130, 213, 120, 25, 177, 54, 116, 227, 131, 171, 86, 86, 96, 197, 225, 114, 0, 119, 160, 188, 184, 182, 59, 225, 44, 88, 251, 106, 155, 49, 57, 157, 228, 42, 140, 210, 178, 67, 109, 132, 109, 249, 168, 54, 208, 237, 247, 178, 139, 22, 135, 184, 168, 179, 80, 93, 24, 74, 125, 209, 179, 43, 41, 95, 98, 194, 146, 199, 189, 139, 158, 145, 9, 202, 200, 9, 94, 199, 245, 207, 232, 89, 74, 66, 102, 144, 240, 55, 151, 105, 124, 12, 42, 184, 120, 205, 77, 73, 135, 97, 61, 155, 225, 218, 146, 119, 195, 145, 68, 252, 15, 133, 80, 171, 145, 8, 59, 249, 164, 80, 203, 167, 168, 163, 1, 79, 126, 175, 146, 76, 157, 181, 78, 125, 225, 15, 73, 92, 171, 123, 235, 67, 12, 7, 167, 151, 64, 224, 190, 118, 81, 4, 147, 165, 215, 50, 212, 124, 171, 207, 241, 137, 44, 102, 236, 165, 143, 143, 108, 23, 179, 124, 38, 127, 10, 19, 168, 233, 105, 174, 195, 11, 215, 169, 17, 207, 30, 219, 22, 21, 116, 147, 19, 89, 21, 123, 144, 171, 164, 65, 100, 86, 152, 109, 1, 89, 110, 25, 41, 0, 162, 92, 128, 94, 103, 232, 228, 114, 155, 73, 182, 140, 200, 227, 178, 127, 251, 145, 111, 170, 225, 113, 163, 205, 244, 255, 139, 22, 162, 169, 55, 41, 144, 208, 71, 197, 205, 53, 14, 39, 206, 210, 151, 28, 186, 149, 115, 86, 156, 100, 162, 236, 28, 101, 191, 23, 60, 56, 80, 249, 101, 180, 119, 142, 211, 139, 19, 107, 67, 214, 221, 231, 29, 21, 151, 11, 173, 216, 103, 38, 197, 145, 74, 0, 78, 63, 130, 85, 36, 221, 136, 127, 175, 104, 131, 214, 81, 109, 92, 236, 87, 158, 208, 197, 126, 23, 214, 135, 33, 233, 132, 16, 109, 100, 74, 65, 241, 101, 233, 155, 131, 148, 78, 114, 164, 82, 167, 81, 255, 86, 212, 80, 39, 48, 185, 226, 175, 111, 102, 249, 254, 24)
[17:42:56 DEBUG STDOUT] send:
[17:42:56 DEBUG STDOUT] b'POST /initialize HTTP/1.1\r\nHost: localhost:7101\r\nUser-Agent: python-requests/2.27.1\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nx-session-identifier: session33367\r\nx-request-identifier: request0\r\nContent-Length: 54165\r\nContent-Type: multipart/form-data; boundary=b1014adf572594b9035171657d522367\r\n\r\n'
[17:42:56 DEBUG STDOUT] send:
[17:42:56 DEBUG STDOUT] b'--b1014adf572594b9035171657d522367\r\nContent-Disposition: form-data; name="encrypted_session_key"\r\nContent-Type: application/octet-stream\r\n\r\n\xe5\x04\xech3\x94\x7f\xa4\xfe\xd9\xdd\\\x17?G\xfe\xf2V\xfc\x1c\xeb\xab\xbc\xf1~h$\xce(\x03\x1f\x1e\x82\xd5x\x19\xb16t\xe3\x83\xabVV`\xc5\xe1r\x00w\xa0\xbc\xb8\xb6;\xe1,X\xfbj\x9b19\x9d\xe4*\x8c\xd2\xb2Cm\x84m\xf9\xa86\xd0\xed\xf7\xb2\x8b\x16\x87\xb8\xa8\xb3P]\x18J}\xd1\xb3+)_b\xc2\x92\xc7\xbd\x8b\x9e\x91\t\xca\xc8\t^\xc7\xf5\xcf\xe8YJBf\x90\xf07\x97i|\x0c*\xb8x\xcdMI\x87a=\x9b\xe1\xda\x92w\xc3\x91D\xfc\x0f\x85P\xab\x91\x08;\xf9\xa4P\xcb\xa7\xa8\xa3\x01O~\xaf\x92L\x9d\xb5N}\xe1\x0fI\\\xab{\xebC\x0c\x07\xa7\x97@\xe0\xbevQ\x04\x93\xa5\xd72\xd4|\xab\xcf\xf1\x89,f\xec\xa5\x8f\x8fl\x17\xb3|&\x7f\n\x13\xa8\xe9i\xae\xc3\x0b\xd7\xa9\x11\xcf\x1e\xdb\x16\x15t\x93\x13Y\x15{\x90\xab\xa4AdV\x98m\x01Yn\x19)\x00\xa2\\\x80^g\xe8\xe4r\x9bI\xb6\x8c\xc8\xe3\xb2\x7f\xfb\x91o\xaa\xe1q\xa3\xcd\xf4\xff\x8b\x16\xa2\xa97)\x90\xd0G\xc5\xcd5\x0e\'\xce\xd2\x97\x1c\xba\x95sV\x9cd\xa2\xec\x1ce\xbf\x17<8P\xf9e\xb4w\x8e\xd3\x8b\x13kC\xd6\xdd\xe7\x1d\x15\x97\x0b\xad\xd8g&\xc5\x91J\x00N?\x82U$\xdd\x88\x7f\xafh\x83\xd6Qm\\\xecW\x9e\xd0\xc5~\x17\xd6\x87!\xe9\x84\x10mdJA\xf1e\xe9\x9b\x83\x94Nr\xa4R\xa7Q\xffV\xd4P\'0\xb9\xe2\xafof\xf9\xfe\x18\r\n--b1014adf572594b9035171657d522367\r\nContent-Disposition: form-data; name="encrypted_request"\r\nContent-Type: application/octet-stream\r\n\r\n$iu\xbbC\xa1\x05\r\x88\xcbe\xebX:\xb2\'\xb2\xd9\xeb\x05g\xed/FS\x8d\xad\x043\xae\x8d\xc8]\xf1\x1dw\x95\x99\xa0\xc8\xe7J\xa1/\xd1\x039\x02R\xa1\'0\xfe$\x87^Eg7<\x19\x87%s\xbdv\xb8\xeer\xa1\x14\t\xb0\x04\xee\xd0\x80$\x04\xe2\xf9\xcb\xf40\xbc\x9c\x95,*\x96\x1em#\xbd\xae\x9eA2L\x90\xac@\xd57\xf2k(s\xb8b\x88\x80<?\x95\xb9\x87\x05;S\xc6\x01\x80\x93v\xb6+\x17a;\x9b\xf0\x06\x84y\x7f\x05v\x02\xcf\x10\xa8~\xab\x9bd\xda9\x02[\xb2\xf2*\x978\x85\r\xb6ea\x99L\xad\xb4\x14\x18\x92d\xff\xff\x9d\xa5l\x81\x8b\xa4\xb9w\xb4\xcb\xf6\x80\x9c\x9e\xd0\x8e\xdc\xf5y\xbc\xd4t\xea\x06y\x0b\xce\x19\xef\xde\xdf\xc5\xbb\xa1\x97n\xb9A\x01\xf2~\xa8tvH\x9e\xb2\xb1\x80X2\xca\n\xaf\xddvt/.\xc4#\x1b\x06\x84\x98\x8c9eD\xcd\xf8\xbc\xdf\xb1\xa3\x1015\xb3:\xe4\xa0\x85s\xf33$\x050w3 rcP\xb3\x1c_\xed\x16H\xb7\xad>\x1f\xf9@\xc7\xa5\xd3\xed4\xa5_J \xe7\x88\xdd\x16{\x80\xff\xfb/Y\xc0\xce\xff\x81K\x07\xc7<w
[truncated]
\x9e\xcc*X2y\xe76\xe6\xa4rb\x84\xdf\x993\xf7y\xd1G\xb8\xa8\xbb\xbe>\x01v\x8fK\xe8\xf4\xffan\x92\xd1\xfc\xc3\x86m\xf03\r\n--b1014adf572594b9035171657d522367--\r\n'
[17:42:56 DEBUG STDOUT] reply:
[17:42:56 DEBUG STDOUT] 'HTTP/1.1 400 Bad Request\r\n'
[17:42:56 DEBUG urllib3.connectionpool] http://localhost:7101 "POST /initialize HTTP/1.1" 400 None
[17:42:56 INFO requests.packages.urllib3] Got response: <Response [400]>
[17:42:56 WARNING pdo.service_client.enclave] [0] network error connecting to service (invoke); 400 Client Error: Bad Request for url: http://localhost:7101/initialize
[17:42:56 WARNING pdo.contract.request] contract invocation failed; 400 Client Error: Bad Request for url: http://localhost:7101/initialize
[17:42:56 ERROR pdo.test.request] failed to create the initial state; contract invocation failed
Traceback (most recent call last):
  File "/home/pyronia/private-data-objects/build/_dev/lib/python3.8/site-packages/pdo_common_library-0.0.1.dev1-py3.8-linux-x86_64.egg/pdo/service_client/enclave.py", line 121, in __send_to_contract__
    response.raise_for_status()
  File "/home/pyronia/private-data-objects/build/_dev/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:7101/initialize

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pyronia/private-data-objects/build/_dev/lib/python3.8/site-packages/pdo_common_library-0.0.1.dev1-py3.8-linux-x86_64.egg/pdo/contract/request.py", line 215, in evaluate
    encrypted_response = self.enclave_service.initialize_contract_state(encrypted_key, encrypted_request)
  File "/home/pyronia/private-data-objects/build/_dev/lib/python3.8/site-packages/pdo_common_library-0.0.1.dev1-py3.8-linux-x86_64.egg/pdo/service_client/enclave.py", line 93, in initialize_contract_state
    return self.__send_to_contract__('initialize', encrypted_session_key, encrypted_request, encoding)
  File "/home/pyronia/private-data-objects/build/_dev/lib/python3.8/site-packages/pdo_common_library-0.0.1.dev1-py3.8-linux-x86_64.egg/pdo/service_client/enclave.py", line 141, in __send_to_contract__
    raise MessageException(str(e)) from e
pdo.service_client.generic.MessageException: 400 Client Error: Bad Request for url: http://localhost:7101/initialize

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pyronia/private-data-objects/build/_dev/lib/python3.8/site-packages/pdo_common_library-0.0.1.dev1-py3.8-linux-x86_64.egg/pdo/test/request.py", line 288, in CreateAndRegisterContract
    initialize_response = initialize_request.evaluate()
  File "/home/pyronia/private-data-objects/build/_dev/lib/python3.8/site-packages/pdo_common_library-0.0.1.dev1-py3.8-linux-x86_64.egg/pdo/contract/request.py", line 219, in evaluate
    raise InvocationException('contract invocation failed') from e
pdo.contract.request.InvocationException: contract invocation failed
[17:42:56 INFO pdo.eservice.pdo_enclave] shutdown enclave
 run-tests.sh: operation failed: pdo-test-request --ledger http://127.0.0.1:6600 --pservice http://localhost:7001/ http://localhost:7002 http://localhost:7003 --eservice-url http://localhost:7101/ --logfile __screen__ --loglevel debug 
```
[eservice1.log](https://github.com/hyperledger-labs/private-data-objects/files/8084915/eservice1.log)

[twisted.log](https://github.com/hyperledger-labs/private-data-objects/files/8084912/twisted.log)

**Comment by marcelamelara** [comment]
Fixed in #362
